name: Deploy to cloudtype
on:
  push:
    branches:
      - dist/server
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: kkoor521/royal-flash
          stage: main
          yaml: >
            name: royal-flash-express

            app: node@18

            options:
              env:
                - name: SERVER_PORT
                  value: "8080"
                - name: DB_URL
                  value: ${{ secrets.DB_URL }}
                - name: ACCESS_SECRET
                  value: ${{ secrets.ACCESS_SECRET }}
                - name: REFRESH_SECRET
                  value: ${{ secrets.REFRESH_SECRET }}
                - name: S3_ACCESS_KEY_ID
                  value: ${{ secrets.S3_ACCESS_KEY_ID }}
                - name: S3_SECRET_ACCESS_KEY
                  value: ${{ secrets.S3_SECRET_ACCESS_KEY }}
                - name: S3_BUCKET_NAME
                  value: ${{ secrets.S3_BUCKET_NAME }}
                - name: S3_REGION
                  value: ${{ secrets.S3_REGION }}
              ports: "8080"
              install: npm i
              build: npm run build
              start: npm start
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
